version: "3"
services:
  pupil_planetary_web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
      - /app/node_modules #ignore local node_modules
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true  
    command: npm run start

